baseURL = "https://vimishra.github.io/"
title = "Vikas's Blog"
paginate = 10
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Vikas's Blog"
description = "A collection of my thoughts, writings and ramblings."
keywords = [
  "Blog",
  "Portfolio",
  "PaperMod"
]
author = "Vikas Mishra"
images = [
  "<link or path of image for opengraph, twitter-cards>"
]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
math = true
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false

  [params.assets]
  favicon = "favicon.ico"
  favicon16x16 = "favicon-16x16.png"
  favicon32x32 = "favicon-32x32.png"
  apple_touch_icon = "apple-touch-icon.png"
  safari_pinned_tab = "apple-touch-icon.png"

  [params.label]
  text = "Vikas's Blog"
  icon = "/apple-touch-icon.png"
  iconHeight = 35.0

  [params.homeInfoParams]
  Title = "Hi there"
  Content = "Welcome to my blog. This is a collection of my thoughts, writings and ramblings. I hope you find something of value here. I am writing it because someone told me that the best way to learn something is to teach someone. That's my attempt here."

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/vimishra"

  [[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/sakivmishra"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://linkedin.com/in/vikmishra"

  [[params.socialIcons]]
  name = "email"
  url = "mailto:vikas.mishra@hey.com"



  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0.0
  distance = 1000.0
  threshold = 0.4
  minMatchCharLength = 0.0
  keys = [
    "title",
    "permalink",
    "summary",
    "content"
  ]

[menu]

  [[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 10.0

  [[menu.main]]
  identifier = "archive"
  name = "Archive"
  url = "/archives/"
  weight = 15.0

  [[menu.main]]
  identifier = "categories"
  name = "Categories"
  url = "/categories/"
  weight = 20.0

  [[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 30.0

  [[menu.main]]
  identifier = "search"
  name = "Search"
  url = "/search/"
  weight = 40.0

[outputs]
home = [
  "HTML",
  "RSS",
  "JSON"
]

# I want to use hugo's chrome to highlight the code.
[markup]
  [markup.highlight]
  codeFences = true
  guessSyntax = true
  lineNos = true
  style = "monokai"
